# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ticket', models.BooleanField(default=False, verbose_name='\u0417\u0430\u044f\u0432\u043a\u0430')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('phone', models.IntegerField(verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='\u0428\u043a\u043e\u043b\u0430')),
                ('stop_reason', models.CharField(blank=True, choices=[('\u041d\u0435 \u0438\u043d\u0442\u0435\u0440\u0435\u0441\u043d\u043e', '\u041d\u0435 \u0438\u043d\u0442\u0435\u0440\u0435\u0441\u043d\u043e'), ('2', '\u0418\u0437\u0443\u0447\u0430\u0435\u0442 \u0432 \u0434\u0440\u0443\u0433\u043e\u0439 \u0448\u043a\u043e\u043b\u0435'), ('3', '\u041e\u0442\u043b\u0438\u0447\u043d\u043e \u0438\u0437\u0443\u0447\u0438\u043b'), ('4', '\u041d\u0430\u0445\u043e\u0434\u0438\u0442\u0441\u044f \u043d\u0435 \u0432 \u0423\u043a\u0440\u0430\u0438\u043d\u0435'), ('5', '\u0412 \u0434\u0440\u0443\u0433\u043e\u043c \u0433\u043e\u0440\u043e\u0434\u0435')], max_length=200, verbose_name='\u041f\u0440\u0438\u0447\u0438\u043d\u0430 \u041e\u0442\u043a\u0430\u0437\u0430')),
                ('recall', models.BooleanField(default=False, verbose_name='\u041f\u0435\u0440\u0435\u0437\u0432\u043e\u043d')),
                ('recall_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0435\u0440\u0435\u0437\u0432\u043e\u043d\u0430')),
                ('creation_date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
        ),
    ]
