# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakUpIn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442'),
        ),
    ]
